name: dpf_notifier
description: Minimal DPF regen notifier prototype
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Notifikace (udržovaný balíček)
  flutter_local_notifications: ^17.2.1

  # Bluetooth
  # ⚠️ starý flutter_bluetooth_serial NEPOUŽÍVAT
  # pokud ti stačí BLE (novější adaptéry), použij:
  flutter_blue_plus: ^1.32.5

  # pokud budeš nutně potřebovat klasický SPP (pro staré ELM327),
  # najdeme společně udržovaný fork nebo řešení přes platform channel

  # Lokalizace
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
